FROM python:3.5-alpine

MAINTAINER Sergii Nuzhdin <ipaq.lw@gmail.com>

RUN apk add --update ca-certificates \
    && apk add postgresql-dev libjpeg tiff-dev zlib-dev \
               libwebp-dev gcc musl-dev linux-headers \
               libxml2-dev libxslt-dev\
    && rm /var/cache/apk/*

ARG PIP_INDEX_URL
ENV PIP_INDEX_URL=${PIP_INDEX_URL}

ARG PIP_TRUSTED_HOST
ENV PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}

ADD requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt
